-- CLEAN RESET
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS user_activity;
DROP TABLE IF EXISTS exchanges;
DROP TABLE IF EXISTS listings;
DROP TABLE IF EXISTS skill_detail;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS users;

-- USERS
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) DEFAULT 'user',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SKILLS (GLOBAL DEFINITIONS)
CREATE TABLE skills (
  id SERIAL PRIMARY KEY,
  title VARCHAR(100) NOT NULL UNIQUE,
  category VARCHAR(100),
  tags TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- USER SKILL DETAILS
CREATE TABLE skill_detail (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  skill_id INT REFERENCES skills(id) ON DELETE CASCADE,
  level VARCHAR(50),
  years_experience INT,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, skill_id)
);

-- LISTINGS (USER POSTS EXCHANGE)
CREATE TABLE listings (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  skill_offered_detail_id INT REFERENCES skill_detail(id) ON DELETE CASCADE,
  skill_requested_id INT REFERENCES skills(id),
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- EXCHANGES
CREATE TABLE exchanges (
  id SERIAL PRIMARY KEY,
  requester_id INT REFERENCES users(id) ON DELETE CASCADE,
  listing_id INT REFERENCES listings(id) ON DELETE CASCADE,
  status VARCHAR(20) DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- MESSAGES
CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  exchange_id INT REFERENCES exchanges(id) ON DELETE CASCADE,
  sender_id INT REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- RATINGS
CREATE TABLE ratings (
  id SERIAL PRIMARY KEY,
  exchange_id INT REFERENCES exchanges(id) ON DELETE CASCADE,
  rater_id INT REFERENCES users(id),
  rated_user_id INT REFERENCES users(id),
  score INT CHECK (score BETWEEN 1 AND 5),
  comment TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(exchange_id, rater_id)
);

-- USER ACTIVITY (AI)
CREATE TABLE user_activity (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(50),
  skill_id INT REFERENCES skills(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);